version: '2'


volumes:
  greyfish:
  influxdb:
  mysql:        


services:


  greyfish:
    build: .
    image: "greyfish/standalone"

    ports:
      - "2000-2004:2000-2004"
    volumes:
      - "greyfish:/greyfish"

    environment:
      - greyfish_key
      - greyfish_path
      - greyfish_threads
      - URL_BASE
      - influx_command
      - redis_command
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

    extends:
      file:
        credentials.yml
      service:
        db_creds

    command: "tail -F anything"


  # Define an InfluxDB service
  influxdb:
    image: influxdb:latest
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
      - "8083:8083"
    extends:
      file:
        credentials.yml
      service:
        db_creds
    command: "$influx_command"


  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "6603:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql

